
import React, { useState, useEffect } from 'react';
import { TransactionType, INCOME_CATEGORIES, EXPENSE_CATEGORIES, Bill } from '../types';
import { Icons, getCategoryIcon } from './Icons';

interface AddBillModalProps {
  initialData?: Bill | null;
  onSave: (bill: Bill | Omit<Bill, 'id'>) => void;
  onClose: () => void;
}

export const AddBillModal: React.FC<AddBillModalProps> = ({ initialData, onSave, onClose }) => {
  const [type, setType] = useState<TransactionType>(TransactionType.EXPENSE);
  const [amount, setAmount] = useState<string>('');
  const [category, setCategory] = useState<string>('');
  const [remark, setRemark] = useState<string>('');
  const [error, setError] = useState<string>('');

  // Initialize form if editing
  useEffect(() => {
    if (initialData) {
      setType(initialData.type);
      setAmount(initialData.amount.toString());
      setCategory(initialData.category);
      setRemark(initialData.remark || '');
    }
  }, [initialData]);

  const categories = type === TransactionType.INCOME ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;

  const handleSave = () => {
    if (!amount || parseFloat(amount) <= 0) {
      setError('请输入有效金额');
      return;
    }
    if (!category) {
      setError('请选择分类');
      return;
    }

    const billData = {
      type,
      amount: parseFloat(amount),
      category,
      remark,
      timestamp: initialData ? initialData.timestamp : Date.now()
    };

    if (initialData) {
      // Return full bill with existing ID for update
      onSave({ ...billData, id: initialData.id });
    } else {
      // Return new bill data (ID generated by service)
      onSave(billData);
    }
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-white flex flex-col animate-in slide-in-from-bottom duration-300">
      {/* Header */}
      <div className="bg-primary text-onPrimary p-4 pt-8 flex items-center justify-between shadow-md">
        <button onClick={onClose} className="p-2 -ml-2 rounded-full hover:bg-white/10">
            <Icons.Back size={24} />
        </button>
        <h2 className="text-lg font-medium">{initialData ? '编辑账单' : '记一笔'}</h2>
        <div className="w-8"></div> {/* Spacer */}
      </div>

      {/* Type Switcher */}
      <div className="p-4 flex gap-4 bg-primary text-onPrimary pb-6">
        <button 
            onClick={() => { setType(TransactionType.EXPENSE); setCategory(''); }}
            className={`flex-1 py-2 rounded-full text-sm font-medium transition-all ${type === TransactionType.EXPENSE ? 'bg-white text-primary shadow-lg' : 'bg-primaryContainer/20 text-white/80'}`}
        >
            支出
        </button>
        <button 
            onClick={() => { setType(TransactionType.INCOME); setCategory(''); }}
            className={`flex-1 py-2 rounded-full text-sm font-medium transition-all ${type === TransactionType.INCOME ? 'bg-white text-primary shadow-lg' : 'bg-primaryContainer/20 text-white/80'}`}
        >
            收入
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 bg-gray-50">
        
        {/* Amount Input */}
        <div className="bg-white p-4 rounded-2xl shadow-sm mb-6">
            <label className="text-xs text-gray-500 uppercase tracking-wide">金额</label>
            <div className="flex items-center text-3xl font-bold text-gray-800 mt-1">
                <span className="text-gray-400 mr-1">¥</span>
                <input 
                    type="number" 
                    value={amount}
                    onChange={(e) => { setAmount(e.target.value); setError(''); }}
                    placeholder="0.00"
                    className="w-full outline-none bg-transparent"
                    autoFocus={!initialData} // Don't autofocus on edit to prevent keyboard jumping
                />
            </div>
            {error && <div className="text-error text-xs mt-2">{error}</div>}
        </div>

        {/* Categories Grid */}
        <div className="mb-6">
            <label className="text-xs text-gray-500 uppercase tracking-wide block mb-3">分类</label>
            <div className="grid grid-cols-4 gap-4">
                {categories.map(cat => {
                    const CatIcon = getCategoryIcon(cat);
                    const isSelected = category === cat;
                    return (
                        <button 
                            key={cat} 
                            onClick={() => { setCategory(cat); setError(''); }}
                            className="flex flex-col items-center gap-2"
                        >
                            <div className={`p-3 rounded-full transition-all duration-200 ${isSelected ? 'bg-primary text-white shadow-md scale-110' : 'bg-white text-gray-500 shadow-sm'}`}>
                                <CatIcon size={20} />
                            </div>
                            <span className={`text-xs ${isSelected ? 'font-bold text-primary' : 'text-gray-500'}`}>{cat}</span>
                        </button>
                    )
                })}
            </div>
        </div>

        {/* Remark */}
        <div className="bg-white p-4 rounded-2xl shadow-sm mb-6">
            <label className="text-xs text-gray-500 uppercase tracking-wide">备注 (选填)</label>
            <input 
                type="text" 
                value={remark}
                onChange={(e) => setRemark(e.target.value)}
                placeholder="写点什么..."
                className="w-full mt-2 outline-none bg-transparent text-gray-700 border-b border-gray-100 pb-2 focus:border-primary transition-colors"
            />
        </div>

      </div>

      {/* Save Button */}
      <div className="p-4 bg-white border-t border-gray-100">
        <button 
            onClick={handleSave}
            className="w-full bg-primary text-white py-3 rounded-full font-bold shadow-lg active:scale-95 transition-transform"
        >
            保存
        </button>
      </div>
    </div>
  );
};
